- src/0.x/theming.md
Functionality PR: https://github.com/rapidez/core/pull/122
> Add documentation for theming multi stores

- src/0.x/faq.md
- src/0.x/tips.md
Change docs to reflect the migration from Turbolinks to Turbo.
> Replace turbolinks with turbo

- src/1.x/upgrading.md
This needs to wait until improve-frontend has been merged
> Add heroicons upgrade guide

- src/1.x/package-development.md
see: https://github.com/rapidez/core/pull/406
> Add new events to the docs

- src/2.x/installation.md
for https://github.com/rapidez/core/pull/478
> [2.x] Update minimum mysql version

- src/2.x/packages.md
Should probably wait for https://github.com/rapidez/sentry/pull/2 to be merged first 😇
> [2.x] Add sentry to packages list

- src/3.x/graphql-components.md
This PR accompanies: https://github.com/rapidez/core/pull/631
> Rename submit fieldsets function

- src/3.x/packages.md
> Added checkout theme and confira in packages

- src/3.x/configuration.md
> Add docs for early hints

- src/.vitepress/config.mjs
- yarn.lock
~~This PR depends on: https://github.com/lucaong/minisearch/pull/282~~
~~Once that is merged and we (or Vitepress) update the version, this will work~~
This has been merged, i've upgraded the package and this PR is ready to merge 🚀
> Filter not matching versions out of search

- spell-check-post.py
- src/3.x/cache.md
- src/3.x/configuration.md
- src/3.x/deployment.md
- src/3.x/extending.md
- src/3.x/faq.md
- src/3.x/graphql-components.md
- src/3.x/indexer.md
- src/3.x/installation.md
- src/3.x/intro.md
- src/3.x/package-development.md
- src/3.x/packages.md
- src/3.x/testing.md
- src/3.x/theming.md
- src/3.x/troubleshooting.md
- src/3.x/upgrading.md
Used OpenAI with the `spell-check-post.py` script, we could automate this with a Github Action later.
> Spell check

- src/3.x/configuration.md
https://github.com/rapidez/core/pull/676
https://github.com/rapidez/checkout-theme/pull/157
todo: confira
> [3.x] Add newsletter configuration

- src/3.x/extending.md
Adds information about store-specific searching as well as expanding on everything else.
> [3.x] Expand on the autocomplete additional indexes

- src/3.x/theming.md
Add information for shadow, ring & outline colors.
Core PR: https://github.com/rapidez/core/pull/691
> Update docs for shadow, ring & outline colors

- src/3.x/packages/statamic.md
Refactored the Statamic docs and added docs for some of the new functionalities.
Also moved the Upgrade Guide from rapidez/statamic to these docs.
> Updated Statamic docs

- src/3.x/theming.md
Updated colors since i've changed them within the core.
> Changed border color contrast

- src/3.x/extending.md
Docs update for https://github.com/rapidez/core/pull/708
> Add fuzziness parameter

- src/3.x/extending.md
For https://github.com/rapidez/core/pull/751
> [3.x] Allow for arbitrary options in additionals

- src/3.x/theming.md
Removed shadow color as we don't use it any more.
> Remove shadow color from docs

- src/4.x/extending.md
This PR to the docs reflects the changes made in https://github.com/rapidez/core/pull/833
> Updated the config to reflect new ES settings

- src/4.x/package-development.md
For: https://github.com/rapidez/core/pull/835
> [4.x] Add and update index mapping/settings

- src/0.x/package-development.md
- src/1.x/configuration.md
- src/1.x/package-development.md
- src/1.x/upgrading.md
- src/2.x/configuration.md
- src/2.x/package-development.md
- src/2.x/upgrading.md
- src/3.x/package-development.md
- src/4.x/package-development.md
Links have been updated to point to the right Rapidez/package versions
Newly added/removed events have been added/removed
Added regular events in a list.
> Tagged repo versions, updated events

- src/4.x/indexer.md
- src/4.x/package-development.md
Depends on https://github.com/rapidez/core/pull/886.
> [4.x] Add documentation on extending mapping/settings in the indexer

- src/4.x/configuration.md
- src/4.x/deployment.md
- src/4.x/extending.md
- src/4.x/faq.md
- src/4.x/indexer.md
- src/4.x/installation.md
- src/4.x/theming.md
- src/4.x/upgrading.md
Docs accompanying: https://github.com/rapidez/core/pull/916
> Added docs for enabling opensearch
